"use client";

import { FormEvent, useEffect, useState } from "react";

type Form = { enabled: boolean; text: string; textAr: string; ctaLabel: string; ctaLabelAr: string; ctaUrl: string; startsAt: string; endsAt: string };
const empty: Form = { enabled: false, text: "", textAr: "", ctaLabel: "", ctaLabelAr: "", ctaUrl: "", startsAt: "", endsAt: "" };
const localDate = (value: string | null) => { if (!value) return ""; const date = new Date(value); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 16); };

export function AnnouncementManager() {
  const [form, setForm] = useState<Form>(empty); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch("/api/admin/announcement").then(async (response) => { if (!response.ok) throw new Error("Unable to load announcement."); const data = await response.json(); if (data) setForm({ enabled: data.announcementEnabled, text: data.announcementText ?? "", textAr: data.announcementTextAr ?? "", ctaLabel: data.announcementCtaLabel ?? "", ctaLabelAr: data.announcementCtaLabelAr ?? "", ctaUrl: data.announcementCtaUrl ?? "", startsAt: localDate(data.announcementStartsAt), endsAt: localDate(data.announcementEndsAt) }); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load announcement.")); }, []);
  function change<Key extends keyof Form>(key: Key, value: Form[Key]) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); const payload = { ...form, text: form.text.trim() || null, textAr: form.textAr.trim() || null, ctaLabel: form.ctaLabel.trim() || null, ctaLabelAr: form.ctaLabelAr.trim() || null, ctaUrl: form.ctaUrl.trim() || null, startsAt: form.startsAt ? new Date(form.startsAt).toISOString() : null, endsAt: form.endsAt ? new Date(form.endsAt).toISOString() : null }; try { const response = await fetch("/api/admin/announcement", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.error ?? "Unable to save announcement."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save announcement."); } finally { setBusy(false); } }
  const input = "rounded border border-black/15 px-3 py-2 font-normal";
  return <form onSubmit={submit} className="grid gap-3 rounded-xl border border-black/10 bg-white p-5 md:grid-cols-2"><h2 className="md:col-span-2 text-lg font-bold">Announcement bar</h2><label className="flex items-center gap-2 text-sm font-medium md:col-span-2"><input type="checkbox" checked={form.enabled} onChange={(event) => change("enabled", event.target.checked)}/> Show on storefront</label><label className="grid gap-1 text-sm font-medium">Text (English)<input value={form.text} onChange={(event) => change("text", event.target.value)} className={input}/></label><label className="grid gap-1 text-sm font-medium">Text (Arabic)<input value={form.textAr} onChange={(event) => change("textAr", event.target.value)} className={input}/></label><label className="grid gap-1 text-sm font-medium">CTA label (English)<input value={form.ctaLabel} onChange={(event) => change("ctaLabel", event.target.value)} className={input}/></label><label className="grid gap-1 text-sm font-medium">CTA label (Arabic)<input value={form.ctaLabelAr} onChange={(event) => change("ctaLabelAr", event.target.value)} className={input}/></label><label className="grid gap-1 text-sm font-medium md:col-span-2">CTA URL (optional)<input value={form.ctaUrl} onChange={(event) => change("ctaUrl", event.target.value)} placeholder="/promotions or https://..." className={input}/></label><label className="grid gap-1 text-sm font-medium">Show from (optional)<input type="datetime-local" value={form.startsAt} onChange={(event) => change("startsAt", event.target.value)} className={input}/></label><label className="grid gap-1 text-sm font-medium">Show until (optional)<input type="datetime-local" value={form.endsAt} onChange={(event) => change("endsAt", event.target.value)} className={input}/></label>{error && <p className="text-sm text-red-600 md:col-span-2">{error}</p>}<button disabled={busy} className="w-fit rounded bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Saving..." : "Save announcement"}</button></form>;
}
