"use client";

import { useEffect, useRef, useState } from "react";

type Branch = { id: string; name: string };
type Product = { id: string; name: string; sku: string | null };
type Transfer = { id: string; transferNumber: string; status: string; sourceBranch: Branch; destinationBranch: Branch; createdAt: string; lines: Array<{ id: string; quantity: number; product: Product }> };

export function InventoryTransfers({ branches }: { branches: Branch[] }) {
  const [transfers, setTransfers] = useState<Transfer[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1);
  const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [lineCount, setLineCount] = useState(1); const [preview, setPreview] = useState<{ summary: { total: number; valid: number; invalid: number }; errors: Array<{ row: number; message: string }> } | null>(null); const [csvFile, setCsvFile] = useState<File | null>(null); const [previewedFile, setPreviewedFile] = useState<File | null>(null); const currentCsvFile = useRef<File | null>(null);
  const [productQuery, setProductQuery] = useState(""); const [deferredProductQuery, setDeferredProductQuery] = useState(""); const [products, setProducts] = useState<Product[]>([]); const [productPage, setProductPage] = useState(1); const [productPages, setProductPages] = useState(0); const [productLoading, setProductLoading] = useState(false); const productRequest = useRef(0);
  async function load() { const response = await fetch(`/api/admin/inventory/transfers?page=${page}&pageSize=10`); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to load transfers."); setTransfers(body.transfers); setPages(body.pagination.totalPages || 1); }
  useEffect(() => { void load().catch((cause) => setError(cause.message)); }, [page]);
  useEffect(() => { const timeout = window.setTimeout(() => setDeferredProductQuery(productQuery), 300); return () => window.clearTimeout(timeout); }, [productQuery]);
  useEffect(() => {
    const query = deferredProductQuery.trim();
    const request = ++productRequest.current;
    if (query.length < 2) { setProducts([]); setProductPages(0); setProductLoading(false); return; }
    const controller = new AbortController();
    setProductLoading(true);
    void fetch(`/api/admin/inventory/products?query=${encodeURIComponent(query)}&page=${productPage}`, { signal: controller.signal })
      .then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to find products."); if (request === productRequest.current) { setProducts(body.products); setProductPages(body.pagination.totalPages); } })
      .catch((cause: unknown) => { if (request === productRequest.current && !(cause instanceof DOMException && cause.name === "AbortError")) setError(cause instanceof Error ? cause.message : "Unable to find products."); })
      .finally(() => { if (request === productRequest.current && !controller.signal.aborted) setProductLoading(false); });
    return () => controller.abort();
  }, [deferredProductQuery, productPage]);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const lines = Array.from(form.getAll("productId")).map((productId, index) => ({ productId: String(productId), quantity: Number(form.getAll("quantity")[index]) })).filter((line) => line.productId && line.quantity > 0); setBusy(true); setError(null); try { const response = await fetch("/api/admin/inventory/transfers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceBranchId: form.get("sourceBranchId"), destinationBranchId: form.get("destinationBranchId"), note: form.get("note") || undefined, lines }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to create transfer."); event.currentTarget.reset(); setLineCount(1); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create transfer."); } finally { setBusy(false); } }
  async function action(id: string, action: "dispatch" | "receive" | "cancel") { setBusy(true); setError(null); try { const response = await fetch(`/api/admin/inventory/transfers/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to update transfer."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update transfer."); } finally { setBusy(false); } }
  async function csv(action: "preview" | "execute", form?: HTMLFormElement) { const file = csvFile; if (!file) return; if (action === "execute") { if (!preview || previewedFile !== file || preview.summary.invalid > 0) return; if (!confirm(`Execute inventory import for ${preview.summary.valid} validated of ${preview.summary.total} rows? This will write the previewed inventory changes.`)) return; } setBusy(true); setError(null); try { const response = await fetch("/api/admin/inventory/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, csv: await file.text() }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to process CSV."); if (action === "preview") { if (currentCsvFile.current === file) { setPreview(body); setPreviewedFile(file); } } else { setPreview(null); setPreviewedFile(null); setCsvFile(null); currentCsvFile.current = null; form?.reset(); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to process CSV."); } finally { setBusy(false); } }
  return <div className="mt-8 space-y-5">
    {error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    <section className="rounded-xl border border-black/10 bg-white p-5"><h2 className="font-bold">New stock transfer</h2><form onSubmit={(event) => void create(event)} className="mt-3 grid gap-3 md:grid-cols-2"><select name="sourceBranchId" required className="rounded border border-black/15 p-2"><option value="">Source branch</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><select name="destinationBranchId" required className="rounded border border-black/15 p-2"><option value="">Destination branch</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><div className="md:col-span-2"><label className="text-sm font-medium">Find products<input value={productQuery} onChange={(event) => { setProductQuery(event.target.value); setProductPage(1); }} minLength={2} placeholder="Search product name or SKU" className="mt-1 block w-full rounded border border-black/15 p-2" /></label><div className="mt-2 flex items-center gap-3 text-xs text-[#666]">{productLoading ? "Searching products..." : productQuery.trim().length < 2 ? "Enter at least two characters to load products." : `${products.length} matching products on this page.`}{productPages > 1 && <><button type="button" disabled={productPage === 1} onClick={() => setProductPage((current) => current - 1)} className="text-brand disabled:opacity-50">Previous results</button><span>Page {productPage} of {productPages}</span><button type="button" disabled={productPage >= productPages} onClick={() => setProductPage((current) => current + 1)} className="text-brand disabled:opacity-50">Next results</button></>}</div></div>{Array.from({ length: lineCount }, (_, index) => <div key={index} className="contents"><select name="productId" required disabled={products.length === 0} className="rounded border border-black/15 p-2 disabled:bg-black/5"><option value="">{products.length ? `Product line ${index + 1}` : "Search for a product first"}</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}{product.sku ? ` (${product.sku})` : ""}</option>)}</select><input name="quantity" type="number" min="1" max="1000000" required placeholder="Quantity" className="rounded border border-black/15 p-2"/></div>)}<button type="button" onClick={() => setLineCount((count) => Math.min(count + 1, 200))} className="w-fit text-sm text-brand">Add line</button><input name="note" maxLength={500} placeholder="Note (optional)" className="rounded border border-black/15 p-2"/><button disabled={busy || products.length === 0} className="w-fit rounded bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Create draft</button></form><p className="mt-2 text-xs text-[#666]">Dispatch reduces only available source stock; receiving increases destination stock.</p></section>
    <section className="rounded-xl border border-black/10 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Inventory CSV</h2><a href="/api/admin/inventory/import" className="text-sm text-brand">Download template</a></div><form className="mt-3 flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); void csv("preview"); }}><input name="csv" type="file" accept=".csv,text/csv" required onChange={(event) => { const file = event.target.files?.[0] ?? null; currentCsvFile.current = file; setCsvFile(file); setPreview(null); setPreviewedFile(null); }} className="text-sm"/><button disabled={busy || !csvFile} className="rounded border border-brand px-3 py-2 text-sm text-brand disabled:opacity-50">Preview</button><button type="button" disabled={busy || !csvFile || previewedFile !== csvFile || !preview || preview.summary.invalid > 0} onClick={(event) => { const form = event.currentTarget.form; if (form) void csv("execute", form); }} className="rounded bg-brand px-3 py-2 text-sm text-white disabled:opacity-50">Execute</button></form>{preview && <p className="mt-3 text-sm">{preview.summary.valid} valid of {preview.summary.total}; {preview.summary.invalid} invalid. {preview.errors.slice(0, 3).map((item) => `Row ${item.row}: ${item.message}`).join(" ")}</p>}</section>
    <section className="overflow-x-auto rounded-xl border border-black/10 bg-white"><table className="w-full text-left text-sm"><thead className="border-b border-black/10 text-[#666]"><tr><th className="px-5 py-3">Transfer</th><th>Route</th><th>Lines</th><th>Status</th><th className="px-5">Action</th></tr></thead><tbody>{transfers.map((transfer) => <tr key={transfer.id} className="border-b border-black/5"><td className="px-5 py-3"><b>{transfer.transferNumber}</b><br/><time className="text-xs text-[#666]">{new Date(transfer.createdAt).toLocaleString()}</time></td><td>{transfer.sourceBranch.name} to {transfer.destinationBranch.name}</td><td>{transfer.lines.map((line) => `${line.product.name} x${line.quantity}`).join(", ")}</td><td>{transfer.status.replace("_", " ")}</td><td className="px-5 py-3 space-x-2">{transfer.status === "DRAFT" && <><button disabled={busy} onClick={() => void action(transfer.id, "dispatch")} className="text-brand">Dispatch</button><button disabled={busy} onClick={() => void action(transfer.id, "cancel")} className="text-red-700">Cancel</button></>}{transfer.status === "IN_TRANSIT" && <><button disabled={busy} onClick={() => void action(transfer.id, "receive")} className="text-brand">Receive</button><button disabled={busy} onClick={() => void action(transfer.id, "cancel")} className="text-red-700">Cancel</button></>}</td></tr>)}{!transfers.length && <tr><td colSpan={5} className="px-5 py-8 text-[#666]">No stock transfers yet.</td></tr>}</tbody></table><div className="flex justify-between p-4 text-sm"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page >= pages} onClick={() => setPage(page + 1)}>Next</button></div></section>
  </div>;
}
