"use client";

import { useEffect, useRef, useState } from "react";

type ErrorRow = { row: number; field?: string; message: string };
type Job = { id: string; status: string; summary: { total?: number; valid?: number; creates?: number; updates?: number; created?: number; updated?: number; failed?: number; processed?: number; progress?: number }; errors: ErrorRow[] | null; createdAt: string; actor: { name: string; email: string } };
type Pagination = { page: number; totalPages: number; total: number };

export function ProductImportManager() {
  const input = useRef<HTMLInputElement>(null); const [csv, setCsv] = useState(""); const [mode, setMode] = useState<"create" | "update" | "upsert">("upsert"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [preview, setPreview] = useState<{ id: string; summary: Job["summary"]; errors: ErrorRow[] } | null>(null); const [jobs, setJobs] = useState<Job[]>([]); const [pagination, setPagination] = useState<Pagination>({ page: 1, totalPages: 0, total: 0 });
  async function load(page = pagination.page) { const response = await fetch(`/api/admin/product-imports?page=${page}`); if (response.ok) { const data = await response.json(); setJobs(data.jobs); setPagination(data.pagination); } }
  useEffect(() => { void load(); }, []);
  async function previewCsv() {
    setBusy(true); setError("");
    try { const response = await fetch("/api/admin/product-imports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv, mode }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to preview CSV."); setPreview({ id: data.job.id, summary: data.job.summary, errors: data.job.errors }); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to preview CSV."); } finally { setBusy(false); }
  }
  async function execute() {
    if (!preview || !confirm("Execute this validated import? Product and inventory values will be written.")) return;
    setBusy(true); setError("");
    try { const response = await fetch(`/api/admin/product-imports/${preview.id}/execute`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Import failed."); setPreview({ id: preview.id, summary: data.summary, errors: data.errors }); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Import failed."); } finally { setBusy(false); }
  }
  return <div className="space-y-6">
    <section className="rounded-xl border border-black/10 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">CSV import</h2><p className="mt-1 max-w-3xl text-sm text-black/65">Each row imports one variant. Use handle plus variant_sku, or an existing variant_public_id. Rows with the same handle are grouped into one product; legacy slug and sku columns remain supported.</p></div><a href="/api/admin/product-imports/template" className="rounded border border-black/15 px-3 py-2 text-sm font-semibold hover:bg-black/5">Download template</a></div><div className="mt-5 grid gap-3"><input ref={input} type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (file) void file.text().then(setCsv); }} className="block w-full text-sm" /><label className="grid max-w-xs gap-1 text-sm font-medium">Import mode<select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)} className="rounded border border-black/15 bg-white p-2 font-normal"><option value="upsert">Create or update</option><option value="create">Create only</option><option value="update">Update only</option></select></label><textarea value={csv} onChange={(event) => setCsv(event.target.value)} placeholder="Paste CSV content, or choose a .csv file" rows={8} className="w-full rounded border border-black/15 p-3 font-mono text-xs" />{error && <p className="text-sm text-red-700">{error}</p>}<div><button type="button" disabled={busy || !csv.trim()} onClick={() => void previewCsv()} className="rounded bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Working..." : "Validate and preview"}</button></div></div></section>
    {preview && <section className="rounded-xl border border-black/10 bg-white p-5"><h2 className="text-lg font-bold">Preview</h2><p className="mt-2 text-sm">{preview.summary.total ?? 0} rows: {preview.summary.valid ?? 0} valid, {preview.summary.creates ?? preview.summary.created ?? 0} creates, {preview.summary.updates ?? preview.summary.updated ?? 0} updates.</p>{preview.errors.length > 0 ? <><p className="mt-3 text-sm font-semibold text-red-700">{preview.errors.length} validation errors. Fix the file and preview again; no data has been written.</p><div className="mt-3 max-h-48 overflow-auto text-sm">{preview.errors.slice(0, 100).map((item, index) => <p key={`${item.row}-${index}`}>Row {item.row}{item.field ? `, ${item.field}` : ""}: {item.message}</p>)}</div><a href={`/api/admin/product-imports/${preview.id}/errors`} className="mt-3 inline-block text-sm font-semibold text-brand">Download error CSV</a></> : <div className="mt-4"><button type="button" disabled={busy} onClick={() => void execute()} className="rounded bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Execute import</button></div>}</section>}
    <section className="overflow-x-auto rounded-xl border border-black/10 bg-white"><div className="border-b px-5 py-4"><h2 className="font-bold">Recent imports</h2></div><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-black/60"><tr><th className="p-3">When</th><th>Administrator</th><th>Status</th><th>Rows</th><th>Result</th><th className="p-3">Errors</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id} className="border-b last:border-0"><td className="p-3">{new Date(job.createdAt).toLocaleString()}</td><td>{job.actor.name}</td><td>{job.status}{job.status === "RUNNING" && ` (${job.summary.progress ?? 0}%)`}</td><td>{job.summary.total ?? 0}</td><td>{job.summary.created ?? job.summary.creates ?? 0} created, {job.summary.updated ?? job.summary.updates ?? 0} updated</td><td className="p-3">{(job.errors?.length ?? 0) > 0 && <a className="text-brand" href={`/api/admin/product-imports/${job.id}/errors`}>CSV ({job.errors?.length})</a>}</td></tr>)}</tbody></table>{jobs.length === 0 && <p className="p-5 text-sm text-black/60">No import jobs yet.</p>}{pagination.totalPages > 1 && <nav aria-label="Import history pagination" className="flex items-center justify-end gap-3 border-t px-5 py-3 text-sm"><span className="text-black/60">Page {pagination.page} of {pagination.totalPages}</span><button type="button" disabled={busy || pagination.page === 1} onClick={() => void load(pagination.page - 1)} className="rounded border border-black/15 px-3 py-1.5 font-semibold disabled:opacity-50">Previous</button><button type="button" disabled={busy || pagination.page === pagination.totalPages} onClick={() => void load(pagination.page + 1)} className="rounded border border-black/15 px-3 py-1.5 font-semibold disabled:opacity-50">Next</button></nav>}</section>
    <p className="text-xs text-black/55">Image URLs must be public HTTPS images smaller than 10 MB. Private-network hosts, unsupported image types, and redirect chains are rejected. ZIP archives remain unavailable until archive scanning is configured.</p>
  </div>;
}
