import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdminPage } from "@/server/auth";
import { db } from "@/server/db";

export default async function AdminCustomerDetailPage({ params }: { params: Promise<{ customerId: string }> }) {
  await requireAdminPage("users");
  const { customerId } = await params;
  const customer = await db.customer.findUnique({ where: { id: customerId }, include: { user: { select: { email: true, status: true, createdAt: true } }, addresses: { include: { area: { include: { province: true } } }, orderBy: { updatedAt: "desc" } }, orders: { select: { id: true, orderNumber: true, status: true, total: true, currencyCode: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 50 } } });
  if (!customer) notFound();
  return <><Link href="/admin/customers" className="text-sm font-semibold text-brand">Back to customers</Link><div className="mt-3"><p className="text-sm font-semibold uppercase tracking-[0.12em] text-brand">Customer profile</p><h1 className="mt-1 text-3xl font-bold">{customer.name}</h1><p className="mt-2 text-sm text-[#666]">{customer.email ?? customer.user?.email ?? "No email"} | {customer.phone} | {customer.user?.status ?? "Guest checkout"}</p></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-black/10 bg-white p-5"><h2 className="text-lg font-bold">Addresses</h2><div className="mt-3 space-y-3">{customer.addresses.map((address) => <div key={address.id} className="border-b border-black/5 pb-3 text-sm last:border-0"><p className="font-medium">{address.type}</p><p>{[address.block && `Block ${address.block}`, address.street && `Street ${address.street}`, address.building && `Building ${address.building}`, address.apartment].filter(Boolean).join(", ") || "No address details"}</p><p className="text-[#666]">{[address.area?.name, address.area?.province.name].filter(Boolean).join(", ")}</p></div>)}{customer.addresses.length === 0 && <p className="mt-3 text-sm text-[#666]">No saved addresses.</p>}</div></section><section className="rounded-xl border border-black/10 bg-white p-5"><h2 className="text-lg font-bold">Recent orders</h2><div className="mt-3 space-y-3">{customer.orders.map((order) => <div key={order.id} className="flex items-center justify-between border-b border-black/5 pb-3 text-sm last:border-0"><div><p className="font-medium">{order.orderNumber}</p><p className="text-[#666]">{new Date(order.createdAt).toLocaleDateString()} | {order.status}</p></div><p>{order.total.toString()} {order.currencyCode}</p></div>)}{customer.orders.length === 0 && <p className="mt-3 text-sm text-[#666]">No orders yet.</p>}</div></section></div></>;
}
